### ISSUE TITLE
Center the TF-IDF before irlba? 

### ISSUE THREAD

**Issue by fransilvion** [pinellolab/scATAC-benchmarking#3]
Hi,

Maybe, I missed this but I am just confused. Why don't you center the TF-IDF matrix before irlba function? This function doesn't do centering by default, and as far as I know, you need to center the data before extracting principal components.

**Comment by huidongchen** [comment]
Hi ,

That's a fair point. To be honest, I haven't tested it out myself so i'm not sure how standardization will affect the final result. 

But here we are trying to benchmark different scATAC methods. We would like to follow the tutorial of the original method as much as possible. 

The tutorial for **_Cusanovich2018_** can be found http://atlas.gs.washington.edu/fly-atac/docs/#usecase1 . There they didn't standardize the data before PCA either. 

But again, it would be nice to explore the difference of with or without standardization as well. I guess it's just a bit beyond the scope of our work.
