### ISSUE TITLE
Download of buenrostro2018.snap

### ISSUE THREAD

**Issue by sebboegel** [pinellolab/scATAC-benchmarking#8]
Is there any chance, that i can download the snap file from the buenrostro2018 example?

Thank you very much

**Comment by huidongchen** [comment]
Hi,

I just added the links to download snap files. You can find the one for `buenrostro2018` dataset here https://github.com/pinellolab/scATAC-benchmarking/tree/master/Real_Data/Buenrostro_2018/run_methods/SnapATAC.

Similarly, you should be able to find the links to snap files for the other datasets.
